sonar.projectKey=SSD-Exam-2402725
sonar.projectName=SSD Exam Webapp
sonar.sources=webapp
sonar.tests=webapp/tests
sonar.exclusions=webapp/node_modules/**,webapp/db/100k-most-used-passwords-NCSC.txt,webapp/tests/**
sonar.test.exclusions=